{{- range $jobName, $job := .Values.jobs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gptscript-bot.fullname" $ }}-{{ $jobName }}-secret
type: Opaque
data:
   {{- range $key, $value := $.Values.global.env }}
   {{ $key }}: {{ $value | b64enc }}
   {{- end }}
  {{- range $key, $value := $job.env }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
---
{{- end }}