apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gptscript-bot.fullname" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs: ["get", "list", "watch", "create"]
  - nonResourceURLs:
      - '*'
    verbs: ["get", "list", "watch", "create"]