apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gptscript-bot.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gptscript-bot.fullname" . }}
    namespace: {{.Release.Namespace}}
roleRef:
  kind: ClusterRole
  name: {{ include "gptscript-bot.fullname" . }}
  apiGroup: rbac.authorization.k8s.io