global:
  env:
    #GPT script combined agent file creation
    AGENTS_REGISTRY_URL: "https://github.com/victorgetz/gptscript-agents/blob/main/agents"
    GITHUB_BASH_URL: "https://github.com/victorgetz/gptscript-agents/blob/main/execute.sh?raw=true"
    MERGED_AGENT_FILE: "tmp/gptscript/combined.gpt"

    #GPT Script
    OPENAI_API_KEY: "REPLACE_ME"
    OPENAI_BASE_URL: "https://ai.iits.tech/backend/api"

    #GIT
    #BOT_TOKEN="$GPTSCRIPT_BOT_TOKEN"
    #GIT_URL="https://$BOT_TOKEN:$BOT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    #BOT_EMAIL="gptscript-bot@iits-consulting.de"
    #BOT_NAME="gptscript-bot"
    #COMMIT_REF="$CI_COMMIT_REF_NAME"

jobs:
  print-pod-names:
    createCronJob: false
    image: "chainguard/gptscript:latest"
    commands:
      - command: "Print out all kubernetes pod names in the current Namespace"
        agents: "base.gpt, kubectl.gpt"
        model: "gpt-4o"
#  gptscript-job-2:
#    createCronJob: true
#    schedule: "0 0 * * *" # Only used if createCronJob is true
#    image: "chainguard/gptscript:latest"
#    commands:
#      - command: "List files in the current directory"
#        agents: "base.gpt, ls.gpt"
#        model: "gpt-4o"