global:
  env:

    #GPT Script

    ## Can also be url like this: github.com/victorgetz/gptscript-agents/gptscript-bot/files/devops-bot.gpt
    GPTSCRIPT_BOT_CONFIG: "/scripts/devops-bot.gpt"
    OPENAI_API_KEY: "sk-..."
    OPENAI_BASE_URL: "https://ai.iits.tech/backend/api"

    #SLACK
    SLACK_WEBHOOK_URL: "REPLACE_ME"

    #GIT
    #BOT_TOKEN="$GPTSCRIPT_BOT_TOKEN"
    #GIT_URL="https://$BOT_TOKEN:$BOT_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    #BOT_EMAIL="gptscript-bot@iits-consulting.de"
    #BOT_NAME="gptscript-bot"
    #COMMIT_REF="$CI_COMMIT_REF_NAME"

jobs:
  fix-pods:
    createCronJob: false
    image: "iits/gptscript:latest"
    commands:
      - command: "Go through all namespaces and take a look at the pods if they seem not to run successfully create summary about it and save it in json format into this file tmp/result.json"
        model: "llm.gpt-4o"
        botConfig: "/scripts/devops-bot.gpt"
      - command: "Read the file tmp/result.json which describes which pods are currently failing in the kubernetes cluster then find out how to fix the kubernetes pods and save it in json format into this file tmp/solution.json"
        model: "llm.gpt-4o"
        botConfig: "/scripts/kubectl-error-solver.gpt"
      - command: "Transform the file tmp/solution.json into a valid slack json message and save it to tmp/message.json"
        model: "llm.gpt-4o"
        botConfig: "/scripts/devops-bot.gpt"
      - command: "Post the slack json message tmp/message.json to this slack webhook url $SLACK_WEBHOOK_URL"
        model: "llm.gpt-4o"
        botConfig: "/scripts/devops-bot.gpt"

  fix-prometheus-alerts:
    createCronJob: false
    image: "iits/gptscript:latest"
    commands:
      # Get errors
      - command: "Curl this endpoint http://prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/prometheus/api/v1/alerts and save it into tmp/prometheus-errors.json"
        model: "llm.gpt-4o"
        botConfig: "/scripts/devops-bot.gpt"

      # Investigate
      - command: "Read the file tmp/prometheus-errors.json which describes current issues in the kubernetes cluster, then find out how to fix them and save it in json format into this file tmp/solution.json"
        model: "llm.gpt-4o"
        botConfig: "/scripts/kubectl-error-solver.gpt"

      # Try to find a solution
      - command: "Transform the file tmp/solution.json into a valid slack json message and save it to tmp/message.json"
        model: "llm.gpt-4o"
        botConfig: "/scripts/devops-bot.gpt"

      - command: "Post the slack json message tmp/message.json to this slack webhook url $SLACK_WEBHOOK_URL"
        model: "llm.gpt-4o"
        botConfig: "/scripts/devops-bot.gpt"